.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. sigecoin_qt test_sigecoin_qt
clean: FORCE
	$(MAKE) -C .. sigecoin_qt_clean test_sigecoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_sigecoin_qt_check
sigecoin-qt sigecoin-qt.exe: FORCE
	 $(MAKE) -C .. sigecoin_qt
